name: CI

on:
  - push
  - pull_request

permissions:
  contents: read

jobs:
  set-matrix:

    name: set matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        data:
          - # shared matrix starts here:
            go-version:
              - "1.23"
    outputs:
      matrix: ${{ toJSON(matrix.data) }}

    steps:
      # `steps` cannot be empty if the job's `uses` is not set
      - run: true

  format:

    name: format
    needs:
      - set-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.set-matrix.outputs.matrix) }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}

    - name: Format
      run: go fmt ./...

    - name: Fix
      run: go fix ./...

    - name: Vet
      run: go vet ./...

    - name: Check changes
      run: git diff-index --quiet HEAD

  unit-test:

    name: unit test
    needs:
      - set-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.set-matrix.outputs.matrix) }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Display Go version
        run: go version

      - name: Install dependencies
        run: go get ./...

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -race -v ./...

  docker:

    name: Docker
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    env:
      REGISTRY: ghcr.io

    steps:
      - uses: actions/checkout@v4

      - name: Set image name
        run: |
          echo "IMAGE_NAME=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Check what needs to be done
        id: need
        env:
          PUSH_DOCKER_IMAGE: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
        run: |
          echo "push_docker_image=$PUSH_DOCKER_IMAGE" >> $GITHUB_OUTPUT

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Log in to the Container registry
        if: ${{ fromJSON(steps.need.outputs.push_docker_image) }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ fromJSON(steps.need.outputs.push_docker_image) }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation
        if: ${{ fromJSON(steps.need.outputs.push_docker_image) }}
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
